# Generated by Django 4.2.15 on 2024-11-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0002_alter_evento_data_ora'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('laboratorio', 'Laboratori e corsi'), ('concerto', 'Concerti'), ('spettacolo', 'Spettacoli ed eventi teatrali'), ('mostra', 'Mostre e installazioni'), ('conferenza', 'Conferenze e convegni'), ('fiera', 'Fiere, sagre, mercatini, festival'), ('live', 'Altri eventi dal vivo')], default='live', max_length=50),
        ),
    ]
