# Generated by Django 4.2.15 on 2024-11-29 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventi', '0004_prenotazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttesaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attese', to='eventi.evento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attese', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attese Evento',
            },
        ),
        migrations.AddConstraint(
            model_name='attesaevento',
            constraint=models.UniqueConstraint(fields=('evento', 'utente'), name='unique_attese'),
        ),
    ]
