# Generated by Django 4.2.15 on 2024-11-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0005_attesaevento_attesaevento_unique_attese'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prenotazione',
            constraint=models.UniqueConstraint(fields=('evento', 'utente'), name='unique_prenotazione'),
        ),
    ]
