# Generated by Django 4.2.15 on 2024-11-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0006_prenotazione_unique_prenotazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='waitlist',
        ),
    ]
