# Generated by Django 4.2.15 on 2024-12-01 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventi', '0007_remove_evento_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='interessi',
            field=models.ManyToManyField(related_name='interessi', to=settings.AUTH_USER_MODEL),
        ),
    ]
