# Generated by Django 4.2.15 on 2024-12-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0008_evento_interessi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnails/eventi/'),
        ),
        migrations.AlterField(
            model_name='luogo',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnails/luoghi/'),
        ),
    ]
