# Generated by Django 4.2.15 on 2024-12-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0010_alter_evento_interessi_alter_evento_luogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='thumbnail',
            field=models.ImageField(default='def_thumbs/thumb_1.jpg', upload_to='thumbnails/eventi/'),
        ),
        migrations.AlterField(
            model_name='luogo',
            name='thumbnail',
            field=models.ImageField(default='def_thumbs/thumb_1.jpg', upload_to='thumbnails/luoghi/'),
        ),
    ]
