# Generated by Django 4.2.15 on 2024-12-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0014_alter_attesaevento_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='image',
            field=models.ImageField(default='def_thumbs/thumb_1.jpg', upload_to='imgs/eventi/'),
        ),
        migrations.AddField(
            model_name='luogo',
            name='image',
            field=models.ImageField(default='def_thumbs/thumb_1.jpg', upload_to='imgs/luoghi/'),
        ),
    ]
