# Generated by Django 4.2.15 on 2024-12-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0016_alter_luogo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='luogo',
            name='thumbnail',
        ),
    ]
