# Generated by Django 4.2.15 on 2024-12-08 13:39

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0017_remove_evento_thumbnail_remove_luogo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=thumbnails.fields.ImageField(default='def_thumbs/thumb_1.jpg', upload_to='imgs/eventi/'),
        ),
        migrations.AlterField(
            model_name='luogo',
            name='image',
            field=thumbnails.fields.ImageField(default='def_thumbs/thumb_1.jpg', upload_to='imgs/luoghi/'),
        ),
    ]
