# Generated by Django 4.2.15 on 2024-12-09 15:17

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0018_alter_evento_image_alter_luogo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=thumbnails.fields.ImageField(default='imgs/def_imgs/thumb_1.jpg', upload_to='imgs/eventi/'),
        ),
        migrations.AlterField(
            model_name='luogo',
            name='image',
            field=thumbnails.fields.ImageField(default='imgs/def_imgs/thumb_1.jpg', upload_to='imgs/luoghi/'),
        ),
    ]
