# Generated by Django 4.2.15 on 2024-12-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0020_alter_evento_posti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='posti',
            field=models.PositiveIntegerField(),
        ),
    ]
