# Generated by Django 4.2.15 on 2024-12-10 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0021_alter_prenotazione_posti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='posti',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
