# Generated by Django 4.2.15 on 2024-12-02 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Promotori',
            },
        ),
        migrations.CreateModel(
            name='Promozione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='promozione/%Y/%m/%d')),
                ('website', models.URLField()),
                ('tags', models.ManyToManyField(blank=True, to='taggit.tag')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promozioni.promotore')),
            ],
            options={
                'verbose_name_plural': 'Promozioni',
            },
        ),
    ]
