# Generated by Django 4.2.15 on 2024-12-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promozioni', '0003_alter_promozione_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promozione',
            name='banner',
            field=models.ImageField(),
        ),
    ]
