# Generated by Django 4.2.15 on 2024-12-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promozioni', '0005_alter_promozione_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='promozione',
            name='visite_anonime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promozione',
            name='visite_registrate',
            field=models.IntegerField(default=0),
        ),
    ]
